package com.briup.apps.poll.bean;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="年级模型")
public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_grade.id
     *
     * @mbg.generated Sun Jun 10 23:12:26 CST 2018
     */
	@ApiModelProperty(value="年级id")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_grade.name
     *
     * @mbg.generated Sun Jun 10 23:12:26 CST 2018
     */
	@ApiModelProperty(value="年级名称")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_grade.description
     *
     * @mbg.generated Sun Jun 10 23:12:26 CST 2018
     */
	@ApiModelProperty(value="年级描述")
    private String description;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_grade.id
     *
     * @return the value of poll_grade.id
     *
     * @mbg.generated Mon Jun 11 11:28:36 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_grade.id
     *
     * @param id the value for poll_grade.id
     *
     * @mbg.generated Mon Jun 11 11:28:36 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_grade.name
     *
     * @return the value of poll_grade.name
     *
     * @mbg.generated Mon Jun 11 11:28:36 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_grade.name
     *
     * @param name the value for poll_grade.name
     *
     * @mbg.generated Mon Jun 11 11:28:36 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_grade.description
     *
     * @return the value of poll_grade.description
     *
     * @mbg.generated Mon Jun 11 11:28:36 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_grade.description
     *
     * @param description the value for poll_grade.description
     *
     * @mbg.generated Mon Jun 11 11:28:36 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}