package com.briup.apps.poll.bean;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="题目选项")
public class Option {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.id
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
	@ApiModelProperty(value="题目选项编号")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.label
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
	@ApiModelProperty(value="题目选项标记",required=true)
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.content
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
	@ApiModelProperty(value="题目选项内容",required=true)
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.score
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
	@ApiModelProperty(value="题目选项分数",required=true)
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_option.question_id
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
	@ApiModelProperty(value="题目选项所关联的题目")
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.id
     *
     * @return the value of poll_option.id
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.id
     *
     * @param id the value for poll_option.id
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.label
     *
     * @return the value of poll_option.label
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.label
     *
     * @param label the value for poll_option.label
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.content
     *
     * @return the value of poll_option.content
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.content
     *
     * @param content the value for poll_option.content
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.score
     *
     * @return the value of poll_option.score
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.score
     *
     * @param score the value for poll_option.score
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_option.question_id
     *
     * @return the value of poll_option.question_id
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_option.question_id
     *
     * @param questionId the value for poll_option.question_id
     *
     * @mbg.generated Tue Jun 12 10:15:00 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

	@Override
	public String toString() {
		return "Option [id=" + id + ", label=" + label + ", content=" + content + ", score=" + score + ", questionId="
				+ questionId + "]";
	}
}