package com.briup.apps.poll.bean;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="题目")
public class Question {
	 /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column poll_question.id
    *
    * @mbg.generated Tue Jun 12 10:23:10 CST 2018
    */
	@ApiModelProperty(value="题目编号")
   private Long id;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column poll_question.title
    *
    * @mbg.generated Tue Jun 12 10:23:10 CST 2018
    */
	@ApiModelProperty(value="题目标题",required=true)
   private String title;

   /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column poll_question.no
    *
    * @mbg.generated Tue Jun 12 10:23:10 CST 2018
    */
	@ApiModelProperty(value="题目序号",required=true)
   private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_question.questionTypeId
     *
     * @mbg.generated Tue Jun 12 11:43:24 CST 2018
     */
	@ApiModelProperty(value="题目类型id",required=true)
    private Long questiontypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_question.questionTypeLabel
     *
     * @mbg.generated Tue Jun 12 11:43:24 CST 2018
     */
	@ApiModelProperty(value="题目类型名称",required=true)
    private String questiontypelabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_question.course_id
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    private Long courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.id
     *
     * @return the value of poll_question.id
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.id
     *
     * @param id the value for poll_question.id
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.no
     *
     * @return the value of poll_question.no
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.no
     *
     * @param no the value for poll_question.no
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.questionTypeId
     *
     * @return the value of poll_question.questionTypeId
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public Long getQuestiontypeid() {
        return questiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.questionTypeId
     *
     * @param questiontypeid the value for poll_question.questionTypeId
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public void setQuestiontypeid(Long questiontypeid) {
        this.questiontypeid = questiontypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.questionTypeLabel
     *
     * @return the value of poll_question.questionTypeLabel
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public String getQuestiontypelabel() {
        return questiontypelabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.questionTypeLabel
     *
     * @param questiontypelabel the value for poll_question.questionTypeLabel
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public void setQuestiontypelabel(String questiontypelabel) {
        this.questiontypelabel = questiontypelabel == null ? null : questiontypelabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.course_id
     *
     * @return the value of poll_question.course_id
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.course_id
     *
     * @param courseId the value for poll_question.course_id
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_question.title
     *
     * @return the value of poll_question.title
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_question.title
     *
     * @param title the value for poll_question.title
     *
     * @mbg.generated Wed Jun 13 11:56:41 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}