package com.briup.apps.poll.bean;

public class Survy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.survyDate
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private String survydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.state
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.code
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.grade_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private Long gradeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.clazz_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private Long clazzId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.course_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.questionnaire_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private Long questionnaireId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_survy.teacher_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    private Long teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.id
     *
     * @return the value of poll_survy.id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.id
     *
     * @param id the value for poll_survy.id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.survyDate
     *
     * @return the value of poll_survy.survyDate
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public String getSurvydate() {
        return survydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.survyDate
     *
     * @param survydate the value for poll_survy.survyDate
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setSurvydate(String survydate) {
        this.survydate = survydate == null ? null : survydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.state
     *
     * @return the value of poll_survy.state
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.state
     *
     * @param state the value for poll_survy.state
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.code
     *
     * @return the value of poll_survy.code
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.code
     *
     * @param code the value for poll_survy.code
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.grade_id
     *
     * @return the value of poll_survy.grade_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public Long getGradeId() {
        return gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.grade_id
     *
     * @param gradeId the value for poll_survy.grade_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setGradeId(Long gradeId) {
        this.gradeId = gradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.clazz_id
     *
     * @return the value of poll_survy.clazz_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public Long getClazzId() {
        return clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.clazz_id
     *
     * @param clazzId the value for poll_survy.clazz_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setClazzId(Long clazzId) {
        this.clazzId = clazzId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.course_id
     *
     * @return the value of poll_survy.course_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.course_id
     *
     * @param courseId the value for poll_survy.course_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.questionnaire_id
     *
     * @return the value of poll_survy.questionnaire_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public Long getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.questionnaire_id
     *
     * @param questionnaireId the value for poll_survy.questionnaire_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setQuestionnaireId(Long questionnaireId) {
        this.questionnaireId = questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_survy.teacher_id
     *
     * @return the value of poll_survy.teacher_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_survy.teacher_id
     *
     * @param teacherId the value for poll_survy.teacher_id
     *
     * @mbg.generated Thu Jun 14 16:09:31 CST 2018
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }
}